/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_Programming;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author lukew
 */
public class TicketPriceCalculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicketPriceCalculator.class.getName());

    /**
     * Creates new form TicketPriceCalculator
     */
    public TicketPriceCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNumTickets = new javax.swing.JTextField();
        orchestra = new javax.swing.JRadioButton();
        mezzanine = new javax.swing.JRadioButton();
        balcony = new javax.swing.JRadioButton();
        btnCalculatePrice = new javax.swing.JToggleButton();
        Matinee = new javax.swing.JRadioButton();
        tfUnitPrice = new javax.swing.JTextField();
        tfTotalPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");

        jLabel1.setText("Num Tickets");

        tfNumTickets.addActionListener(this::tfNumTicketsActionPerformed);

        buttonGroup1.add(orchestra);
        orchestra.setText("Orchestra");
        orchestra.addActionListener(this::orchestraActionPerformed);

        buttonGroup1.add(mezzanine);
        mezzanine.setText("Mezzanine");

        buttonGroup1.add(balcony);
        balcony.setText("Balcony");

        btnCalculatePrice.setText("Calc Price");
        btnCalculatePrice.addActionListener(this::btnCalculatePriceActionPerformed);

        Matinee.setText("Matinee");

        jLabel2.setText("Price Each");

        jLabel3.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mezzanine, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orchestra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(Matinee, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalculatePrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNumTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matinee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orchestra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mezzanine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balcony)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculatePrice)
                    .addComponent(tfUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumTicketsActionPerformed

    private void orchestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orchestraActionPerformed

    }//GEN-LAST:event_orchestraActionPerformed

    private void btnCalculatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculatePriceActionPerformed
        JOptionPane alert = new JOptionPane();
        
        int num_tickets = 0;
        double total_price = 0;
        try{
            num_tickets = Integer.parseInt(tfNumTickets.getText());
        } catch(NumberFormatException e){
            alert.showMessageDialog(null, "Please enter a valid number of tickets","Error" , alert.ERROR_MESSAGE);
        }
        if (Matinee.isSelected()) {
            if (orchestra.isSelected()){
                total_price = (num_tickets * 85 * 0.85);
                tfUnitPrice.setText("$" +String.valueOf(85 * 0.85));
            } else if (mezzanine.isSelected()) {
                total_price = (num_tickets * 70 * 0.85);
                tfUnitPrice.setText("$" +String.valueOf(70*0.85));
            } else if (balcony.isSelected()) {
                total_price = (num_tickets * 45 * 0.85);
                tfUnitPrice.setText("$" +String.valueOf(45*0.85));
            } else {
                    alert.showMessageDialog(null, "Please select one of the options.","Error" , alert.ERROR_MESSAGE);
            }
        } else {
            if (orchestra.isSelected()){
                total_price = (num_tickets * 85);
                tfUnitPrice.setText("$" +String.valueOf(85));
            } else if (mezzanine.isSelected()) {
                total_price = (num_tickets * 70);
                tfUnitPrice.setText("$" +String.valueOf(70));
            } else if (balcony.isSelected()) {
                total_price = (num_tickets * 45);
                tfUnitPrice.setText("$" +String.valueOf(45));
            } else {
                    alert.showMessageDialog(null, "Please select one of the options.","Error" , alert.ERROR_MESSAGE);
            }
        }
        tfTotalPrice.setText("$" + String.valueOf(total_price));
    }//GEN-LAST:event_btnCalculatePriceActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicketPriceCalculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Matinee;
    private javax.swing.JRadioButton balcony;
    private javax.swing.JToggleButton btnCalculatePrice;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mezzanine;
    private javax.swing.JRadioButton orchestra;
    private javax.swing.JTextField tfNumTickets;
    private javax.swing.JTextField tfTotalPrice;
    private javax.swing.JTextField tfUnitPrice;
    // End of variables declaration//GEN-END:variables
}

